In [1]:
import numpy as np
import scipy.linalg as sla

In [8]:
a = np.array([[1, 2, 4], [5, 6, 7], [8, 7, 9]])
a

array([[1, 2, 4],
       [5, 6, 7],
       [8, 7, 9]])

In [9]:
sla.inv(a)

array([[-0.2 , -0.4 ,  0.4 ],
       [-0.44,  0.92, -0.52],
       [ 0.52, -0.36,  0.16]])

In [10]:
sla.eig(a)

(array([17.19489424+0.j, -1.94313023+0.j,  0.74823599+0.j]),
 array([[-0.26134635, -0.79866476,  0.32777091],
        [-0.59296553, -0.02704881, -0.85310746],
        [-0.76163637,  0.601168  ,  0.4059235 ]]))

In [11]:
sla.eigvals(a)

array([17.19489424+0.j, -1.94313023+0.j,  0.74823599+0.j])

In [12]:
sla.det(a)

-25.000000000000004

In [13]:
sla.norm(a)

18.027756377319946

In [15]:
sla.lu(a)

(array([[0., 0., 1.],
        [0., 1., 0.],
        [1., 0., 0.]]),
 array([[1.        , 0.        , 0.        ],
        [0.625     , 1.        , 0.        ],
        [0.125     , 0.69230769, 1.        ]]),
 array([[8.        , 7.        , 9.        ],
        [0.        , 1.625     , 1.375     ],
        [0.        , 0.        , 1.92307692]]))

In [16]:
sla.svd(a)

(array([[-0.23771972, -0.88811043, -0.39338175],
        [-0.58419293, -0.1928339 ,  0.78837409],
        [-0.77602059,  0.41722291, -0.47298742]]),
 array([17.91435476,  1.8769964 ,  0.74349046]),
 array([[-0.52286835, -0.5254301 , -0.67121673],
        [ 0.79142579, -0.00674688, -0.61122803],
        [-0.31662898,  0.85081002, -0.41936666]]))

In [17]:
sla.expm(a)

array([[ 3985817.12929743,  4139576.66751154,  5481499.63191011],
       [ 9043369.94065946,  9392237.25591003, 12436905.62067421],
       [11615785.1278799 , 12063885.12692581, 15974622.75092574]])

In [18]:
sla.logm(a)

array([[0.83825634+2.31301963j, 0.55535257+0.3728953j ,
        0.25609193-1.08399931j],
       [0.98956194+0.07833629j, 0.7168211 +0.01262905j,
        1.31701765-0.03671239j],
       [0.71159361-1.74104764j, 1.20306922-0.28068438j,
        1.66379839+0.81594398j]])

In [19]:
sla.sinm(a)

array([[-0.73407059, -0.42779986,  0.24301547],
       [-0.55681255,  0.1373166 , -0.69164836],
       [ 0.2296874 , -0.54516633, -0.65086521]])